language: bash

services:
  - docker

branches:
  only:
    - main

before_script:
  - export IMAGE_TAG="${GCR_HOSTNAME}/${GCR_PROJECT_ID}/$(basename ${TRAVIS_REPO_SLUG})"
  - echo "${IMAGE_TAG}"

script:
  - docker build --no-cache --tag "${IMAGE_TAG}:latest" ./airflow
