language: bash

services:
  - docker

branches:
  only:
    - master

before_script:
  - export IMAGE_TAG="${GCR_HOSTNAME}/${GCR_PROJECT_ID}/$(basename ${TRAVIS_REPO_SLUG})"

script:
  - echo "${IMAGE_TAG}"
  - docker build --no-cache --tag "${IMAGE_TAG}:latest" ./airflow
